blank_issues_enabled: false
contact_links:
  - name: Questions and Support
    url: https://github.com/SirTidez/Schedule-I-Developement-Environement-Manager/discussions
    about: Please ask and answer questions here.

